### ISSUE TITLE
a small bug on mac

### ISSUE THREAD

**Issue by alex123-2star** [laluka/bypass-url-parser#1]
I found a small bug on mac 
code
～～～
#your code on mac
echo -e "\e[34m----------------------\e[0m"
<img width="367" alt="image" src="https://user-images.githubusercontent.com/63630525/158182769-0a9a2173-a613-47b1-8c4a-09f4b9378c8d.png">

#my code on mac
echo "\033[30m black color  \033[0m"

～～～
<img width="526" alt="image" src="https://user-images.githubusercontent.com/63630525/158182054-7d033e6a-060a-4adb-9f36-f7b1b1029750.png">

run
<img width="408" alt="image" src="https://user-images.githubusercontent.com/63630525/158182854-96fee4ce-759e-47fd-ae6f-7e8dff877dec.png">

Your color code is not implemented and printed directly on the mac
Thank you for your software, thank you for your efforts

**Comment by nuoxoxo** [comment]
This is not a bug in itself. 
On MacOS, just use `printf` to properly display color when you `make`.
On Linux, it is `echo` that works.

**Comment by laluka** [comment]
Hey guys, I don't own a mac, would you mind writing a PR for these changes ?
Is they work on linux as well I'll merge them! 💟 

Also, I might write a dockerfile for this so you can still benefit of it to the full :)

**Comment by laluka** [comment]
Well, just remembered there's no echo anymore, so it's "solved" haha

**Comment by laluka** [comment]
Moved from bash to python :)
