### ISSUE TITLE
Add new payload/technique `,.js`

### ISSUE THREAD

**Issue by ElSicarius** [laluka/bypass-url-parser#38]
Hi there,

I recently found a bypass that BUP didn't find:

I had a `/index.php` that redirected to `https://othersite.com/auth`

I noticed that all the `.js` files returned a `200 OK`

Using `/index.php/,.js` I was able to bypass the restrictions and access the app.

The extensions that also worked:
```
.js
.css
.gif
.jpe?g
.png
.class
.docx
.xls
```
Can you add this technique to BUP please ? :)

Cheers,

**Comment by laluka** [comment]
Yo yo !

![image](https://github.com/laluka/bypass-url-parser/assets/7013722/c5e96482-b783-4b3e-b823-5e40d85ca4b4)

Will add in the upcoming days/weeks, thanks ! ;)

**Comment by laluka** [comment]
Added within #40  ! ^.^

**Comment by ElSicarius** [comment]
nice ! thanks :+1:
